---
- name: create new win EC2 instances for escrow
  local_action:
      module: ec2
     # key_name: "{{ key_name }}"
      region: "{{ region }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      image: "{{ image }}"
      instance_type: "{{instance_type_of_servers}}"
      #group: "{{security_group_name}}"
      group_id: "{{ sg_out.group_id }}"
      wait: yes
      instance_tags:
            Name: "win_escrow"
      count: "{{instance_count}}"
      user_data: "{{ lookup('template', 'userdata.txt.j2') }}"
  register: ec2

- name: Add new win_escrow private IPs to host group
  add_host: hostname={{  item.private_ip }} groups=WinEscrowMachines
  with_items: '{{ec2.instances}}'

- name: wait for WinRM to answer on all hosts
  wait_for:
    port: 5986
    host: "{{ item.private_ip }}"
    timeout: 300
  with_items: '{{ec2.instances}}'


