---
# This playbook creats new instance on EC2 that will be used as a machine for new newman agent installation
- name: create new EC2 instances for new newman agents
  local_action:
      module: ec2
      key_name: "{{ key_name }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type_of_servers }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      group: "{{security_group_name}}"
      image: "{{ image }}"
      wait: yes
      #assign_public_ip: yes
      instance_tags:
        Name: "escrow"
      count: "{{instance_count}}"
  register: ec2

- name: Add new escrow machine private IPs to host group
  add_host: hostname={{  item.private_ip }} groups=EscrowMachines
  with_items: '{{ec2.instances}}'

- name: Wait for SSH to come up
  wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=600 state=started
  with_items: '{{ec2.instances}}'



